use evdev::Key;

#[allow(non_camel_case_types)]
#[derive(Copy, Clone, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum MOD_MASK {
    MASK_SHIFT,
    MASK_CTRL,
    MASK_ALT,
    MASK_META,
    MASK_CAPSLOCK,
    MASK_NUMLOCK,
    MASK_SCROLLLOCK,
}

impl TryFrom<Key> for MOD_MASK {
    type Error = ();

    fn try_from(key: Key) -> Result<Self, ()> {
        match key {
            Key::KEY_LEFTSHIFT | Key::KEY_RIGHTSHIFT => Ok(Self::MASK_SHIFT),
            Key::KEY_LEFTCTRL | Key::KEY_RIGHTCTRL => Ok(Self::MASK_CTRL),
            Key::KEY_LEFTALT | Key::KEY_RIGHTALT => Ok(Self::MASK_ALT),
            Key::KEY_LEFTMETA | Key::KEY_RIGHTMETA => Ok(Self::MASK_META),
            Key::KEY_CAPSLOCK => Ok(Self::MASK_CAPSLOCK),
            Key::KEY_NUMLOCK => Ok(Self::MASK_NUMLOCK),
            Key::KEY_SCROLLLOCK => Ok(Self::MASK_SCROLLLOCK),
            _ => Err(()),
        }
    }
}

pub fn is_modifier(key: &Key) -> bool {
    matches!(
        key,
        &Key::KEY_LEFTSHIFT
            | &Key::KEY_RIGHTSHIFT
            | &Key::KEY_LEFTCTRL
            | &Key::KEY_RIGHTCTRL
            | &Key::KEY_LEFTALT
            | &Key::KEY_RIGHTALT
            | &Key::KEY_LEFTMETA
            | &Key::KEY_RIGHTMETA
            | &Key::KEY_CAPSLOCK
            | &Key::KEY_NUMLOCK
            | &Key::KEY_SCROLLLOCK
    )
}

pub fn into_mods(keys: &[String]) -> Vec<MOD_MASK> {
    let mut result = Vec::new();
    for key in keys {
        if let Some(key) = into_mod(key) {
            result.push(key);
        }
    }
    result
}

pub fn into_mod(key: &str) -> Option<MOD_MASK> {
    match key {
        "Shift" => Some(MOD_MASK::MASK_SHIFT),
        "Ctrl" => Some(MOD_MASK::MASK_CTRL),
        "Alt" => Some(MOD_MASK::MASK_ALT),
        "Meta" => Some(MOD_MASK::MASK_META),
        "Capslock" => Some(MOD_MASK::MASK_CAPSLOCK),
        "Numlock" => Some(MOD_MASK::MASK_NUMLOCK),
        "Scrolllock" => Some(MOD_MASK::MASK_SCROLLLOCK),
        _ => None,
    }
}

pub fn into_keys(keys: &[String]) -> Vec<Key> {
    let mut result = Vec::new();
    for key in keys {
        if let Some(key) = into_key(key) {
            result.push(key);
        }
    }
    result
}

// We allow this because this function is simply a mapping wrapper.
#[allow(clippy::too_many_lines)]
#[must_use]
pub fn into_key(key: &str) -> Option<Key> {
    match key {
        "Reserved" => Some(Key::KEY_RESERVED),
        "Escape" => Some(Key::KEY_ESC),
        "1" => Some(Key::KEY_1),
        "2" => Some(Key::KEY_2),
        "3" => Some(Key::KEY_3),
        "4" => Some(Key::KEY_4),
        "5" => Some(Key::KEY_5),
        "6" => Some(Key::KEY_6),
        "7" => Some(Key::KEY_7),
        "8" => Some(Key::KEY_8),
        "9" => Some(Key::KEY_9),
        "0" => Some(Key::KEY_0),
        "Minus" => Some(Key::KEY_MINUS),
        "Equal" => Some(Key::KEY_EQUAL),
        "Backspace" => Some(Key::KEY_BACKSPACE),
        "Tab" => Some(Key::KEY_TAB),
        "q" => Some(Key::KEY_Q),
        "w" => Some(Key::KEY_W),
        "e" => Some(Key::KEY_E),
        "r" => Some(Key::KEY_R),
        "t" => Some(Key::KEY_T),
        "y" => Some(Key::KEY_Y),
        "u" => Some(Key::KEY_U),
        "i" => Some(Key::KEY_I),
        "o" => Some(Key::KEY_O),
        "p" => Some(Key::KEY_P),
        "Leftbrace" => Some(Key::KEY_LEFTBRACE),
        "Rightbrace" => Some(Key::KEY_RIGHTBRACE),
        "Enter" => Some(Key::KEY_ENTER),
        "Leftctrl" => Some(Key::KEY_LEFTCTRL),
        "a" => Some(Key::KEY_A),
        "s" => Some(Key::KEY_S),
        "d" => Some(Key::KEY_D),
        "f" => Some(Key::KEY_F),
        "g" => Some(Key::KEY_G),
        "h" => Some(Key::KEY_H),
        "j" => Some(Key::KEY_J),
        "k" => Some(Key::KEY_K),
        "l" => Some(Key::KEY_L),
        "Semicolon" => Some(Key::KEY_SEMICOLON),
        "Apostrophe" => Some(Key::KEY_APOSTROPHE),
        "Grave" => Some(Key::KEY_GRAVE),
        "Leftshift" => Some(Key::KEY_LEFTSHIFT),
        "Backslash" => Some(Key::KEY_BACKSLASH),
        "z" => Some(Key::KEY_Z),
        "x" => Some(Key::KEY_X),
        "c" => Some(Key::KEY_C),
        "v" => Some(Key::KEY_V),
        "b" => Some(Key::KEY_B),
        "n" => Some(Key::KEY_N),
        "m" => Some(Key::KEY_M),
        "Comma" => Some(Key::KEY_COMMA),
        "Dot" => Some(Key::KEY_DOT),
        "Slash" => Some(Key::KEY_SLASH),
        "Rightshift" => Some(Key::KEY_RIGHTSHIFT),
        "Kpasterisk" => Some(Key::KEY_KPASTERISK),
        "Leftalt" => Some(Key::KEY_LEFTALT),
        "Space" => Some(Key::KEY_SPACE),
        "Capslock" => Some(Key::KEY_CAPSLOCK),
        "F1" => Some(Key::KEY_F1),
        "F2" => Some(Key::KEY_F2),
        "F3" => Some(Key::KEY_F3),
        "F4" => Some(Key::KEY_F4),
        "F5" => Some(Key::KEY_F5),
        "F6" => Some(Key::KEY_F6),
        "F7" => Some(Key::KEY_F7),
        "F8" => Some(Key::KEY_F8),
        "F9" => Some(Key::KEY_F9),
        "F10" => Some(Key::KEY_F10),
        "Numlock" => Some(Key::KEY_NUMLOCK),
        "Scrolllock" => Some(Key::KEY_SCROLLLOCK),
        "Kp7" => Some(Key::KEY_KP7),
        "Kp8" => Some(Key::KEY_KP8),
        "Kp9" => Some(Key::KEY_KP9),
        "Kpminus" => Some(Key::KEY_KPMINUS),
        "Kp4" => Some(Key::KEY_KP4),
        "Kp5" => Some(Key::KEY_KP5),
        "Kp6" => Some(Key::KEY_KP6),
        "Kpplus" => Some(Key::KEY_KPPLUS),
        "Kp1" => Some(Key::KEY_KP1),
        "Kp2" => Some(Key::KEY_KP2),
        "Kp3" => Some(Key::KEY_KP3),
        "Kp0" => Some(Key::KEY_KP0),
        "Kpdot" => Some(Key::KEY_KPDOT),
        "Zenkakuhankaku" => Some(Key::KEY_ZENKAKUHANKAKU),
        "102nd" => Some(Key::KEY_102ND),
        "F11" => Some(Key::KEY_F11),
        "F12" => Some(Key::KEY_F12),
        "Ro" => Some(Key::KEY_RO),
        "Katakana" => Some(Key::KEY_KATAKANA),
        "Hiragana" => Some(Key::KEY_HIRAGANA),
        "Henkan" => Some(Key::KEY_HENKAN),
        "Katakanahiragana" => Some(Key::KEY_KATAKANAHIRAGANA),
        "Muhenkan" => Some(Key::KEY_MUHENKAN),
        "Kpjpcomma" => Some(Key::KEY_KPJPCOMMA),
        "Kpenter" => Some(Key::KEY_KPENTER),
        "Rightctrl" => Some(Key::KEY_RIGHTCTRL),
        "Kpslash" => Some(Key::KEY_KPSLASH),
        "Sysrq" => Some(Key::KEY_SYSRQ),
        "Rightalt" => Some(Key::KEY_RIGHTALT),
        "Linefeed" => Some(Key::KEY_LINEFEED),
        "Home" => Some(Key::KEY_HOME),
        "Up" => Some(Key::KEY_UP),
        "Pageup" => Some(Key::KEY_PAGEUP),
        "Left" => Some(Key::KEY_LEFT),
        "Right" => Some(Key::KEY_RIGHT),
        "End" => Some(Key::KEY_END),
        "Down" => Some(Key::KEY_DOWN),
        "Pagedown" => Some(Key::KEY_PAGEDOWN),
        "Insert" => Some(Key::KEY_INSERT),
        "Delete" => Some(Key::KEY_DELETE),
        "Macro" => Some(Key::KEY_MACRO),
        "Mute" => Some(Key::KEY_MUTE),
        "Volumedown" => Some(Key::KEY_VOLUMEDOWN),
        "Volumeup" => Some(Key::KEY_VOLUMEUP),
        "Power" => Some(Key::KEY_POWER),
        "Kpequal" => Some(Key::KEY_KPEQUAL),
        "Kpplusminus" => Some(Key::KEY_KPPLUSMINUS),
        "Pause" => Some(Key::KEY_PAUSE),
        "Scale" => Some(Key::KEY_SCALE),
        "Kpcomma" => Some(Key::KEY_KPCOMMA),
        "Hangeul" => Some(Key::KEY_HANGEUL),
        "Hanja" => Some(Key::KEY_HANJA),
        "Yen" => Some(Key::KEY_YEN),
        "Leftmeta" => Some(Key::KEY_LEFTMETA),
        "Rightmeta" => Some(Key::KEY_RIGHTMETA),
        "Compose" => Some(Key::KEY_COMPOSE),
        "Stop" => Some(Key::KEY_STOP),
        "Again" => Some(Key::KEY_AGAIN),
        "Props" => Some(Key::KEY_PROPS),
        "Undo" => Some(Key::KEY_UNDO),
        "Front" => Some(Key::KEY_FRONT),
        "Copy" => Some(Key::KEY_COPY),
        "Open" => Some(Key::KEY_OPEN),
        "Paste" => Some(Key::KEY_PASTE),
        "Find" => Some(Key::KEY_FIND),
        "Cut" => Some(Key::KEY_CUT),
        "Help" => Some(Key::KEY_HELP),
        "Menu" => Some(Key::KEY_MENU),
        "Calc" => Some(Key::KEY_CALC),
        "Setup" => Some(Key::KEY_SETUP),
        "Sleep" => Some(Key::KEY_SLEEP),
        "Wakeup" => Some(Key::KEY_WAKEUP),
        "File" => Some(Key::KEY_FILE),
        "Sendfile" => Some(Key::KEY_SENDFILE),
        "Deletefile" => Some(Key::KEY_DELETEFILE),
        "Xfer" => Some(Key::KEY_XFER),
        "Prog1" => Some(Key::KEY_PROG1),
        "Prog2" => Some(Key::KEY_PROG2),
        "Www" => Some(Key::KEY_WWW),
        "Msdos" => Some(Key::KEY_MSDOS),
        "Coffee" => Some(Key::KEY_COFFEE),
        "Rotate_display" => Some(Key::KEY_ROTATE_DISPLAY),
        "Cyclewindows" => Some(Key::KEY_CYCLEWINDOWS),
        "Mail" => Some(Key::KEY_MAIL),
        "Bookmarks" => Some(Key::KEY_BOOKMARKS),
        "Computer" => Some(Key::KEY_COMPUTER),
        "Back" => Some(Key::KEY_BACK),
        "Forward" => Some(Key::KEY_FORWARD),
        "Closecd" => Some(Key::KEY_CLOSECD),
        "Ejectcd" => Some(Key::KEY_EJECTCD),
        "Ejectclosecd" => Some(Key::KEY_EJECTCLOSECD),
        "Nextsong" => Some(Key::KEY_NEXTSONG),
        "Playpause" => Some(Key::KEY_PLAYPAUSE),
        "Previoussong" => Some(Key::KEY_PREVIOUSSONG),
        "Stopcd" => Some(Key::KEY_STOPCD),
        "Record" => Some(Key::KEY_RECORD),
        "Rewind" => Some(Key::KEY_REWIND),
        "Phone" => Some(Key::KEY_PHONE),
        "Iso" => Some(Key::KEY_ISO),
        "Config" => Some(Key::KEY_CONFIG),
        "Homepage" => Some(Key::KEY_HOMEPAGE),
        "Refresh" => Some(Key::KEY_REFRESH),
        "Exit" => Some(Key::KEY_EXIT),
        "Move" => Some(Key::KEY_MOVE),
        "Edit" => Some(Key::KEY_EDIT),
        "Scrollup" => Some(Key::KEY_SCROLLUP),
        "Scrolldown" => Some(Key::KEY_SCROLLDOWN),
        "Kpleftparen" => Some(Key::KEY_KPLEFTPAREN),
        "Kprightparen" => Some(Key::KEY_KPRIGHTPAREN),
        "New" => Some(Key::KEY_NEW),
        "Redo" => Some(Key::KEY_REDO),
        "F13" => Some(Key::KEY_F13),
        "F14" => Some(Key::KEY_F14),
        "F15" => Some(Key::KEY_F15),
        "F16" => Some(Key::KEY_F16),
        "F17" => Some(Key::KEY_F17),
        "F18" => Some(Key::KEY_F18),
        "F19" => Some(Key::KEY_F19),
        "F20" => Some(Key::KEY_F20),
        "F21" => Some(Key::KEY_F21),
        "F22" => Some(Key::KEY_F22),
        "F23" => Some(Key::KEY_F23),
        "F24" => Some(Key::KEY_F24),
        "Playcd" => Some(Key::KEY_PLAYCD),
        "Pausecd" => Some(Key::KEY_PAUSECD),
        "Prog3" => Some(Key::KEY_PROG3),
        "Prog4" => Some(Key::KEY_PROG4),
        "Dashboard" => Some(Key::KEY_DASHBOARD),
        "Suspend" => Some(Key::KEY_SUSPEND),
        "Close" => Some(Key::KEY_CLOSE),
        "Play" => Some(Key::KEY_PLAY),
        "Fastforward" => Some(Key::KEY_FASTFORWARD),
        "Bassboost" => Some(Key::KEY_BASSBOOST),
        "Print" => Some(Key::KEY_PRINT),
        "Hp" => Some(Key::KEY_HP),
        "Camera" => Some(Key::KEY_CAMERA),
        "Sound" => Some(Key::KEY_SOUND),
        "Question" => Some(Key::KEY_QUESTION),
        "Email" => Some(Key::KEY_EMAIL),
        "Chat" => Some(Key::KEY_CHAT),
        "Search" => Some(Key::KEY_SEARCH),
        "Connect" => Some(Key::KEY_CONNECT),
        "Finance" => Some(Key::KEY_FINANCE),
        "Sport" => Some(Key::KEY_SPORT),
        "Shop" => Some(Key::KEY_SHOP),
        "Alterase" => Some(Key::KEY_ALTERASE),
        "Cancel" => Some(Key::KEY_CANCEL),
        "Brightnessdown" => Some(Key::KEY_BRIGHTNESSDOWN),
        "Brightnessup" => Some(Key::KEY_BRIGHTNESSUP),
        "Media" => Some(Key::KEY_MEDIA),
        "Switchvideomode" => Some(Key::KEY_SWITCHVIDEOMODE),
        "Kbdillumtoggle" => Some(Key::KEY_KBDILLUMTOGGLE),
        "Kbdillumdown" => Some(Key::KEY_KBDILLUMDOWN),
        "Kbdillumup" => Some(Key::KEY_KBDILLUMUP),
        "Send" => Some(Key::KEY_SEND),
        "Reply" => Some(Key::KEY_REPLY),
        "Forwardmail" => Some(Key::KEY_FORWARDMAIL),
        "Save" => Some(Key::KEY_SAVE),
        "Documents" => Some(Key::KEY_DOCUMENTS),
        "Battery" => Some(Key::KEY_BATTERY),
        "Bluetooth" => Some(Key::KEY_BLUETOOTH),
        "Wlan" => Some(Key::KEY_WLAN),
        "Uwb" => Some(Key::KEY_UWB),
        "Unknown" => Some(Key::KEY_UNKNOWN),
        "Video_next" => Some(Key::KEY_VIDEO_NEXT),
        "Video_prev" => Some(Key::KEY_VIDEO_PREV),
        "Brightness_cycle" => Some(Key::KEY_BRIGHTNESS_CYCLE),
        "Brightness_auto" => Some(Key::KEY_BRIGHTNESS_AUTO),
        "Display_off" => Some(Key::KEY_DISPLAY_OFF),
        "Wwan" => Some(Key::KEY_WWAN),
        "Rfkill" => Some(Key::KEY_RFKILL),
        "Micmute" => Some(Key::KEY_MICMUTE),
        "Ok" => Some(Key::KEY_OK),
        "Select" => Some(Key::KEY_SELECT),
        "Goto" => Some(Key::KEY_GOTO),
        "Clear" => Some(Key::KEY_CLEAR),
        "Power2" => Some(Key::KEY_POWER2),
        "Option" => Some(Key::KEY_OPTION),
        "Info" => Some(Key::KEY_INFO),
        "Time" => Some(Key::KEY_TIME),
        "Vendor" => Some(Key::KEY_VENDOR),
        "Archive" => Some(Key::KEY_ARCHIVE),
        "Program" => Some(Key::KEY_PROGRAM),
        "Channel" => Some(Key::KEY_CHANNEL),
        "Favorites" => Some(Key::KEY_FAVORITES),
        "Epg" => Some(Key::KEY_EPG),
        "Pvr" => Some(Key::KEY_PVR),
        "Mhp" => Some(Key::KEY_MHP),
        "Language" => Some(Key::KEY_LANGUAGE),
        "Title" => Some(Key::KEY_TITLE),
        "Subtitle" => Some(Key::KEY_SUBTITLE),
        "Angle" => Some(Key::KEY_ANGLE),
        "Full_screen" => Some(Key::KEY_FULL_SCREEN),
        "Mode" => Some(Key::KEY_MODE),
        "Keyboard" => Some(Key::KEY_KEYBOARD),
        "Screen" => Some(Key::KEY_SCREEN),
        "Pc" => Some(Key::KEY_PC),
        "Tv" => Some(Key::KEY_TV),
        "Tv2" => Some(Key::KEY_TV2),
        "Vcr" => Some(Key::KEY_VCR),
        "Vcr2" => Some(Key::KEY_VCR2),
        "Sat" => Some(Key::KEY_SAT),
        "Sat2" => Some(Key::KEY_SAT2),
        "Cd" => Some(Key::KEY_CD),
        "Tape" => Some(Key::KEY_TAPE),
        "Radio" => Some(Key::KEY_RADIO),
        "Tuner" => Some(Key::KEY_TUNER),
        "Player" => Some(Key::KEY_PLAYER),
        "Text" => Some(Key::KEY_TEXT),
        "Dvd" => Some(Key::KEY_DVD),
        "Aux" => Some(Key::KEY_AUX),
        "Mp3" => Some(Key::KEY_MP3),
        "Audio" => Some(Key::KEY_AUDIO),
        "Video" => Some(Key::KEY_VIDEO),
        "Directory" => Some(Key::KEY_DIRECTORY),
        "List" => Some(Key::KEY_LIST),
        "Memo" => Some(Key::KEY_MEMO),
        "Calendar" => Some(Key::KEY_CALENDAR),
        "Red" => Some(Key::KEY_RED),
        "Green" => Some(Key::KEY_GREEN),
        "Yellow" => Some(Key::KEY_YELLOW),
        "Blue" => Some(Key::KEY_BLUE),
        "Channelup" => Some(Key::KEY_CHANNELUP),
        "Channeldown" => Some(Key::KEY_CHANNELDOWN),
        "First" => Some(Key::KEY_FIRST),
        "Last" => Some(Key::KEY_LAST),
        "Ab" => Some(Key::KEY_AB),
        "Next" => Some(Key::KEY_NEXT),
        "Restart" => Some(Key::KEY_RESTART),
        "Slow" => Some(Key::KEY_SLOW),
        "Shuffle" => Some(Key::KEY_SHUFFLE),
        "Break" => Some(Key::KEY_BREAK),
        "Previous" => Some(Key::KEY_PREVIOUS),
        "Digits" => Some(Key::KEY_DIGITS),
        "Teen" => Some(Key::KEY_TEEN),
        "Twen" => Some(Key::KEY_TWEN),
        "Videophone" => Some(Key::KEY_VIDEOPHONE),
        "Games" => Some(Key::KEY_GAMES),
        "Zoomin" => Some(Key::KEY_ZOOMIN),
        "Zoomout" => Some(Key::KEY_ZOOMOUT),
        "Zoomreset" => Some(Key::KEY_ZOOMRESET),
        "Wordprocessor" => Some(Key::KEY_WORDPROCESSOR),
        "Editor" => Some(Key::KEY_EDITOR),
        "Spreadsheet" => Some(Key::KEY_SPREADSHEET),
        "Graphicseditor" => Some(Key::KEY_GRAPHICSEDITOR),
        "Presentation" => Some(Key::KEY_PRESENTATION),
        "Database" => Some(Key::KEY_DATABASE),
        "News" => Some(Key::KEY_NEWS),
        "Voicemail" => Some(Key::KEY_VOICEMAIL),
        "Addressbook" => Some(Key::KEY_ADDRESSBOOK),
        "Messenger" => Some(Key::KEY_MESSENGER),
        "Displaytoggle" => Some(Key::KEY_DISPLAYTOGGLE),
        "Spellcheck" => Some(Key::KEY_SPELLCHECK),
        "Logoff" => Some(Key::KEY_LOGOFF),
        "Dollar" => Some(Key::KEY_DOLLAR),
        "Euro" => Some(Key::KEY_EURO),
        "Frameback" => Some(Key::KEY_FRAMEBACK),
        "Frameforward" => Some(Key::KEY_FRAMEFORWARD),
        "Context_menu" => Some(Key::KEY_CONTEXT_MENU),
        "Media_repeat" => Some(Key::KEY_MEDIA_REPEAT),
        "10channelsup" => Some(Key::KEY_10CHANNELSUP),
        "10channelsdown" => Some(Key::KEY_10CHANNELSDOWN),
        "Images" => Some(Key::KEY_IMAGES),
        "Del_eol" => Some(Key::KEY_DEL_EOL),
        "Del_eos" => Some(Key::KEY_DEL_EOS),
        "Ins_line" => Some(Key::KEY_INS_LINE),
        "Del_line" => Some(Key::KEY_DEL_LINE),
        "Fn" => Some(Key::KEY_FN),
        "Fn_esc" => Some(Key::KEY_FN_ESC),
        "Fn_f1" => Some(Key::KEY_FN_F1),
        "Fn_f2" => Some(Key::KEY_FN_F2),
        "Fn_f3" => Some(Key::KEY_FN_F3),
        "Fn_f4" => Some(Key::KEY_FN_F4),
        "Fn_f5" => Some(Key::KEY_FN_F5),
        "Fn_f6" => Some(Key::KEY_FN_F6),
        "Fn_f7" => Some(Key::KEY_FN_F7),
        "Fn_f8" => Some(Key::KEY_FN_F8),
        "Fn_f9" => Some(Key::KEY_FN_F9),
        "Fn_f10" => Some(Key::KEY_FN_F10),
        "Fn_f11" => Some(Key::KEY_FN_F11),
        "Fn_f12" => Some(Key::KEY_FN_F12),
        "Fn_1" => Some(Key::KEY_FN_1),
        "Fn_2" => Some(Key::KEY_FN_2),
        "Fn_d" => Some(Key::KEY_FN_D),
        "Fn_e" => Some(Key::KEY_FN_E),
        "Fn_f" => Some(Key::KEY_FN_F),
        "Fn_s" => Some(Key::KEY_FN_S),
        "Fn_b" => Some(Key::KEY_FN_B),
        "Brl_dot1" => Some(Key::KEY_BRL_DOT1),
        "Brl_dot2" => Some(Key::KEY_BRL_DOT2),
        "Brl_dot3" => Some(Key::KEY_BRL_DOT3),
        "Brl_dot4" => Some(Key::KEY_BRL_DOT4),
        "Brl_dot5" => Some(Key::KEY_BRL_DOT5),
        "Brl_dot6" => Some(Key::KEY_BRL_DOT6),
        "Brl_dot7" => Some(Key::KEY_BRL_DOT7),
        "Brl_dot8" => Some(Key::KEY_BRL_DOT8),
        "Brl_dot9" => Some(Key::KEY_BRL_DOT9),
        "Brl_dot10" => Some(Key::KEY_BRL_DOT10),
        "Numeric_0" => Some(Key::KEY_NUMERIC_0),
        "Numeric_1" => Some(Key::KEY_NUMERIC_1),
        "Numeric_2" => Some(Key::KEY_NUMERIC_2),
        "Numeric_3" => Some(Key::KEY_NUMERIC_3),
        "Numeric_4" => Some(Key::KEY_NUMERIC_4),
        "Numeric_5" => Some(Key::KEY_NUMERIC_5),
        "Numeric_6" => Some(Key::KEY_NUMERIC_6),
        "Numeric_7" => Some(Key::KEY_NUMERIC_7),
        "Numeric_8" => Some(Key::KEY_NUMERIC_8),
        "Numeric_9" => Some(Key::KEY_NUMERIC_9),
        "Numeric_star" => Some(Key::KEY_NUMERIC_STAR),
        "Numeric_pound" => Some(Key::KEY_NUMERIC_POUND),
        "Numeric_a" => Some(Key::KEY_NUMERIC_A),
        "Numeric_b" => Some(Key::KEY_NUMERIC_B),
        "Numeric_c" => Some(Key::KEY_NUMERIC_C),
        "Numeric_d" => Some(Key::KEY_NUMERIC_D),
        "Camera_focus" => Some(Key::KEY_CAMERA_FOCUS),
        "Wps_button" => Some(Key::KEY_WPS_BUTTON),
        "Touchpad_toggle" => Some(Key::KEY_TOUCHPAD_TOGGLE),
        "Touchpad_on" => Some(Key::KEY_TOUCHPAD_ON),
        "Touchpad_off" => Some(Key::KEY_TOUCHPAD_OFF),
        "Camera_zoomin" => Some(Key::KEY_CAMERA_ZOOMIN),
        "Camera_zoomout" => Some(Key::KEY_CAMERA_ZOOMOUT),
        "Camera_up" => Some(Key::KEY_CAMERA_UP),
        "Camera_down" => Some(Key::KEY_CAMERA_DOWN),
        "Camera_left" => Some(Key::KEY_CAMERA_LEFT),
        "Camera_right" => Some(Key::KEY_CAMERA_RIGHT),
        "Attendant_on" => Some(Key::KEY_ATTENDANT_ON),
        "Attendant_off" => Some(Key::KEY_ATTENDANT_OFF),
        "Attendant_toggle" => Some(Key::KEY_ATTENDANT_TOGGLE),
        "Lights_toggle" => Some(Key::KEY_LIGHTS_TOGGLE),
        "Als_toggle" => Some(Key::KEY_ALS_TOGGLE),
        "Buttonconfig" => Some(Key::KEY_BUTTONCONFIG),
        "Taskmanager" => Some(Key::KEY_TASKMANAGER),
        "Journal" => Some(Key::KEY_JOURNAL),
        "Controlpanel" => Some(Key::KEY_CONTROLPANEL),
        "Appselect" => Some(Key::KEY_APPSELECT),
        "Screensaver" => Some(Key::KEY_SCREENSAVER),
        "Voicecommand" => Some(Key::KEY_VOICECOMMAND),
        "Assistant" => Some(Key::KEY_ASSISTANT),
        "Kbd_layout_next" => Some(Key::KEY_KBD_LAYOUT_NEXT),
        "Brightness_min" => Some(Key::KEY_BRIGHTNESS_MIN),
        "Brightness_max" => Some(Key::KEY_BRIGHTNESS_MAX),
        "Kbdinputassist_prev" => Some(Key::KEY_KBDINPUTASSIST_PREV),
        "Kbdinputassist_next" => Some(Key::KEY_KBDINPUTASSIST_NEXT),
        "Kbdinputassist_prevgroup" => Some(Key::KEY_KBDINPUTASSIST_PREVGROUP),
        "Kbdinputassist_nextgroup" => Some(Key::KEY_KBDINPUTASSIST_NEXTGROUP),
        "Kbdinputassist_accept" => Some(Key::KEY_KBDINPUTASSIST_ACCEPT),
        "Kbdinputassist_cancel" => Some(Key::KEY_KBDINPUTASSIST_CANCEL),
        "Right_up" => Some(Key::KEY_RIGHT_UP),
        "Right_down" => Some(Key::KEY_RIGHT_DOWN),
        "Left_up" => Some(Key::KEY_LEFT_UP),
        "Left_down" => Some(Key::KEY_LEFT_DOWN),
        "Root_menu" => Some(Key::KEY_ROOT_MENU),
        "Media_top_menu" => Some(Key::KEY_MEDIA_TOP_MENU),
        "Numeric_11" => Some(Key::KEY_NUMERIC_11),
        "Numeric_12" => Some(Key::KEY_NUMERIC_12),
        "Audio_desc" => Some(Key::KEY_AUDIO_DESC),
        "3d_mode" => Some(Key::KEY_3D_MODE),
        "Next_favorite" => Some(Key::KEY_NEXT_FAVORITE),
        "Stop_record" => Some(Key::KEY_STOP_RECORD),
        "Pause_record" => Some(Key::KEY_PAUSE_RECORD),
        "Vod" => Some(Key::KEY_VOD),
        "Unmute" => Some(Key::KEY_UNMUTE),
        "Fastreverse" => Some(Key::KEY_FASTREVERSE),
        "Slowreverse" => Some(Key::KEY_SLOWREVERSE),
        "Data" => Some(Key::KEY_DATA),
        "Onscreen_keyboard" => Some(Key::KEY_ONSCREEN_KEYBOARD),
        "Privacy_screen_toggle" => Some(Key::KEY_PRIVACY_SCREEN_TOGGLE),
        "Selective_screenshot" => Some(Key::KEY_SELECTIVE_SCREENSHOT),
        "Btn_0" => Some(Key::BTN_0),
        "Btn_1" => Some(Key::BTN_1),
        "Btn_2" => Some(Key::BTN_2),
        "Btn_3" => Some(Key::BTN_3),
        "Btn_4" => Some(Key::BTN_4),
        "Btn_5" => Some(Key::BTN_5),
        "Btn_6" => Some(Key::BTN_6),
        "Btn_7" => Some(Key::BTN_7),
        "Btn_8" => Some(Key::BTN_8),
        "Btn_9" => Some(Key::BTN_9),
        "Btn_left" => Some(Key::BTN_LEFT),
        "Btn_right" => Some(Key::BTN_RIGHT),
        "Btn_middle" => Some(Key::BTN_MIDDLE),
        "Btn_side" => Some(Key::BTN_SIDE),
        "Btn_extra" => Some(Key::BTN_EXTRA),
        "Btn_forward" => Some(Key::BTN_FORWARD),
        "Btn_back" => Some(Key::BTN_BACK),
        "Btn_task" => Some(Key::BTN_TASK),
        "Btn_trigger" => Some(Key::BTN_TRIGGER),
        "Btn_thumb" => Some(Key::BTN_THUMB),
        "Btn_thumb2" => Some(Key::BTN_THUMB2),
        "Btn_top" => Some(Key::BTN_TOP),
        "Btn_top2" => Some(Key::BTN_TOP2),
        "Btn_pinkie" => Some(Key::BTN_PINKIE),
        "Btn_base" => Some(Key::BTN_BASE),
        "Btn_base2" => Some(Key::BTN_BASE2),
        "Btn_base3" => Some(Key::BTN_BASE3),
        "Btn_base4" => Some(Key::BTN_BASE4),
        "Btn_base5" => Some(Key::BTN_BASE5),
        "Btn_base6" => Some(Key::BTN_BASE6),
        "Btn_dead" => Some(Key::BTN_DEAD),
        "Btn_south" => Some(Key::BTN_SOUTH),
        "Btn_east" => Some(Key::BTN_EAST),
        "Btn_c" => Some(Key::BTN_C),
        "Btn_north" => Some(Key::BTN_NORTH),
        "Btn_west" => Some(Key::BTN_WEST),
        "Btn_z" => Some(Key::BTN_Z),
        "Btn_tl" => Some(Key::BTN_TL),
        "Btn_tr" => Some(Key::BTN_TR),
        "Btn_tl2" => Some(Key::BTN_TL2),
        "Btn_tr2" => Some(Key::BTN_TR2),
        "Btn_select" => Some(Key::BTN_SELECT),
        "Btn_start" => Some(Key::BTN_START),
        "Btn_mode" => Some(Key::BTN_MODE),
        "Btn_thumbl" => Some(Key::BTN_THUMBL),
        "Btn_thumbr" => Some(Key::BTN_THUMBR),
        "Btn_tool_pen" => Some(Key::BTN_TOOL_PEN),
        "Btn_tool_rubber" => Some(Key::BTN_TOOL_RUBBER),
        "Btn_tool_brush" => Some(Key::BTN_TOOL_BRUSH),
        "Btn_tool_pencil" => Some(Key::BTN_TOOL_PENCIL),
        "Btn_tool_airbrush" => Some(Key::BTN_TOOL_AIRBRUSH),
        "Btn_tool_finger" => Some(Key::BTN_TOOL_FINGER),
        "Btn_tool_mouse" => Some(Key::BTN_TOOL_MOUSE),
        "Btn_tool_lens" => Some(Key::BTN_TOOL_LENS),
        "Btn_tool_quinttap" => Some(Key::BTN_TOOL_QUINTTAP),
        "Btn_touch" => Some(Key::BTN_TOUCH),
        "Btn_stylus" => Some(Key::BTN_STYLUS),
        "Btn_stylus2" => Some(Key::BTN_STYLUS2),
        "Btn_tool_doubletap" => Some(Key::BTN_TOOL_DOUBLETAP),
        "Btn_tool_tripletap" => Some(Key::BTN_TOOL_TRIPLETAP),
        "Btn_tool_quadtap" => Some(Key::BTN_TOOL_QUADTAP),
        "Btn_gear_down" => Some(Key::BTN_GEAR_DOWN),
        "Btn_gear_up" => Some(Key::BTN_GEAR_UP),
        "Btn_dpad_up" => Some(Key::BTN_DPAD_UP),
        "Btn_dpad_down" => Some(Key::BTN_DPAD_DOWN),
        "Btn_dpad_left" => Some(Key::BTN_DPAD_LEFT),
        "Btn_dpad_right" => Some(Key::BTN_DPAD_RIGHT),
        "Btn_trigger_happy1" => Some(Key::BTN_TRIGGER_HAPPY1),
        "Btn_trigger_happy2" => Some(Key::BTN_TRIGGER_HAPPY2),
        "Btn_trigger_happy3" => Some(Key::BTN_TRIGGER_HAPPY3),
        "Btn_trigger_happy4" => Some(Key::BTN_TRIGGER_HAPPY4),
        "Btn_trigger_happy5" => Some(Key::BTN_TRIGGER_HAPPY5),
        "Btn_trigger_happy6" => Some(Key::BTN_TRIGGER_HAPPY6),
        "Btn_trigger_happy7" => Some(Key::BTN_TRIGGER_HAPPY7),
        "Btn_trigger_happy8" => Some(Key::BTN_TRIGGER_HAPPY8),
        "Btn_trigger_happy9" => Some(Key::BTN_TRIGGER_HAPPY9),
        "Btn_trigger_happy10" => Some(Key::BTN_TRIGGER_HAPPY10),
        "Btn_trigger_happy11" => Some(Key::BTN_TRIGGER_HAPPY11),
        "Btn_trigger_happy12" => Some(Key::BTN_TRIGGER_HAPPY12),
        "Btn_trigger_happy13" => Some(Key::BTN_TRIGGER_HAPPY13),
        "Btn_trigger_happy14" => Some(Key::BTN_TRIGGER_HAPPY14),
        "Btn_trigger_happy15" => Some(Key::BTN_TRIGGER_HAPPY15),
        "Btn_trigger_happy16" => Some(Key::BTN_TRIGGER_HAPPY16),
        "Btn_trigger_happy17" => Some(Key::BTN_TRIGGER_HAPPY17),
        "Btn_trigger_happy18" => Some(Key::BTN_TRIGGER_HAPPY18),
        "Btn_trigger_happy19" => Some(Key::BTN_TRIGGER_HAPPY19),
        "Btn_trigger_happy20" => Some(Key::BTN_TRIGGER_HAPPY20),
        "Btn_trigger_happy21" => Some(Key::BTN_TRIGGER_HAPPY21),
        "Btn_trigger_happy22" => Some(Key::BTN_TRIGGER_HAPPY22),
        "Btn_trigger_happy23" => Some(Key::BTN_TRIGGER_HAPPY23),
        "Btn_trigger_happy24" => Some(Key::BTN_TRIGGER_HAPPY24),
        "Btn_trigger_happy25" => Some(Key::BTN_TRIGGER_HAPPY25),
        "Btn_trigger_happy26" => Some(Key::BTN_TRIGGER_HAPPY26),
        "Btn_trigger_happy27" => Some(Key::BTN_TRIGGER_HAPPY27),
        "Btn_trigger_happy28" => Some(Key::BTN_TRIGGER_HAPPY28),
        "Btn_trigger_happy29" => Some(Key::BTN_TRIGGER_HAPPY29),
        "Btn_trigger_happy30" => Some(Key::BTN_TRIGGER_HAPPY30),
        "Btn_trigger_happy31" => Some(Key::BTN_TRIGGER_HAPPY31),
        "Btn_trigger_happy32" => Some(Key::BTN_TRIGGER_HAPPY32),
        "Btn_trigger_happy33" => Some(Key::BTN_TRIGGER_HAPPY33),
        "Btn_trigger_happy34" => Some(Key::BTN_TRIGGER_HAPPY34),
        "Btn_trigger_happy35" => Some(Key::BTN_TRIGGER_HAPPY35),
        "Btn_trigger_happy36" => Some(Key::BTN_TRIGGER_HAPPY36),
        "Btn_trigger_happy37" => Some(Key::BTN_TRIGGER_HAPPY37),
        "Btn_trigger_happy38" => Some(Key::BTN_TRIGGER_HAPPY38),
        "Btn_trigger_happy39" => Some(Key::BTN_TRIGGER_HAPPY39),
        "Btn_trigger_happy40" => Some(Key::BTN_TRIGGER_HAPPY40),
        _ => None,
    }
}
