[package]
name = "lefthk"
version = "0.1.0"
edition = "2018"

[dependencies]
clap = "2.3.0"
kdl = "3.0.0"
log = "0.4.14"
mio = "0.7.14"
nix = "0.23.0"
pretty_env_logger = "0.4.0"
serde = { version = "1.0.130", features = ["derive"] }
serde_kdl = "0.1.0"
thiserror = "1.0.30"
tokio = { version = "1.12.0", features = ["fs", "io-util", "macros", "net", "rt-multi-thread", "sync", "time"] }
x11-dl = "2.19.1"
xdg = "2.4.0"

[dev-dependencies]
tempfile = "3.2.0"
